blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('category/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path('detail/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('comment/<int:post_pk>/', views.CommentView.as_view(), name='comment'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

blog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Category(models.Model):
  name = models.CharField('カテゴリ名', max_length=255)

  def __str__(self):
    return self.name

class Post(models.Model):
  title = models.CharField('title', max_length=255)
  text = models.TextField('本文')
  create_at = models.DateTimeField('作成日', default=timezone.now)
  category = models.ForeignKey(Category, verbose_name='カテゴリ名', on_delete=models.PROTECT)

  def __str__(self):
    return self.title



class Comment(models.Model):
  name = models.CharField('お名前', max_length=30, default='名無し')
  text = models.TextField('本文')
  post = models.ForeignKey(Post, verbose_name='紐づく記事', on_delete=models.PROTECT) #コメントを全て削除しないと投稿を消せない仕様
  create_at = models.DateTimeField('作成日', default=timezone.now)
  def __str__(self):
    return self.text[:10]

blog/forms.py
from django import forms
from .models import Comment


class CommentCreateForm(forms.ModelForm): #コメントモデルをもとに入力欄を生成してくれる

  # 入力欄のカスタマイズをしてる
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    for field in self.fields.values():
      field.widget.attrs['class'] = 'form-control'
  
  class Meta:
    model = Comment
    fields = ['name', 'text'] #本文と入力欄だけ表示される

blog/views.py
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect
from django.views import generic
from .forms import CommentCreateForm
from .models import Post, Category, Comment


class IndexView(generic.ListView):
  model = Post
  paginate_by = 1

  def get_queryset(self): #新しい記事から表示する
    queryset = Post.objects.order_by('-create_at')
    keyword = self.request.GET.get('keyword') #formで指定したkeywordを取得する 検索フォームの入力内容を取得できる
    if keyword :
      queryset=queryset.filter( #フィールド名__icontains=keywordでキーワードが含むかどうかで検索することができる　完全一致の場合はフィールド名=keywordで良い
        Q(title__icontains=keyword)|Q(text__icontains=keyword)) #Qでor検索ができる　これで本文にマッチしたkeywordも取得することができる
    return queryset
  


class CategoryView(generic.ListView):
  model = Post #CategoryViewといってもそのカテゴリで絞り込んだ記事の一覧なのでListViewでモデルはPostになる
  paginate_by = 10

  def get_queryset(self):
    category = get_object_or_404(Category, pk=self.kwargs['pk']) #カテゴリオブジェクトを取得している pkでカテゴリオブジェクトがなければ404ページに遷移させる
    queryset = Post.objects.order_by('-create_at').filter(category=category) #降順かつcategoryでヒットしたものだけ取得する
    # category_pk = self.kwargs['pk']
    # queryset = Post.objects.order_by('-created_at').filter(category__pk=category_pk)
    return queryset



class DetailView(generic.DetailView):
  model = Post


# コメント投稿ページに移動する際に記事のプライマリーキーをURLに含めてコメント投稿のviewに渡すことでどの記事に紐づいたコメント
# なのかがすぐにわかり、そのプライマリーキーで記事を取得してその記事をコメントに紐づける
class CommentView(generic.CreateView):
  model = Comment
  # fields = ('name', 'text')
  form_class = CommentCreateForm

  def form_valid(self, form):
    post_pk = self.kwargs['post_pk']
    comment = form.save(commit=False)
    comment.post = get_object_or_404(Post, pk=post_pk)
    comment.save()
    return redirect('blog:detail', pk=post_pk)

blog/templates/blog/base.html
<!doctype html>
<html lang="ja">
  <head>
    <title>ブログ</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
      <a class="navbar-brand" href="#">blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'blog:index' %}">Home</a>
          </li>
          <!-- スーパーユーザーだけ表示される -->
          {% if user.is_superuser %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">admin</a>
          </li>
          {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'blog:index' %}">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="keyword">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
    
    <div class="jumbotron">
      <h1 class="display-3">ブログタイトル!</h1>
      <p class="lead">OOに関するブログ</p>
      <hr class="my-2">

      <p class="lead">
        <a class="btn btn-primary btn-lg" href="#!" role="button">Some action</a>
      </p>
    </div>
    

    <div class="container">
      <div class="row">
        <div class="col-md-8">
          {% block content %}
          {% endblock %}
        </div>
        <div class="col-md-4">
          <ul class="list-group">
            <li class="list-group-item bg-dark text-center">カテゴリ一覧</li>
            {% for category in category_list %}
            <!-- カテゴリで絞り込む -->
            <li class="list-group-item"><a href="{% url 'blog:category' category.pk %}">{{ category }}</a></li> 
          </ul>
          {% endfor %}
        </div>
      </div>
    </div>
    <footer class="bg-dark text-white text-center py-3">Satoshi</footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}

{% block content %}

<!-- actionを空文字のままデータを送信する。コメントフォームを作成するのにコメント投稿用のviewにGETでアクセスしてこのテンプレートが表示される。コメントを送信するときはフォーム内の送信ボタンでまた同じページにpostで送信する。つまり一つのviewでGETとPOSTの両方を処理する -->
<form action="" method="POST">
  {{ form.non_field_errors }}
  <!-- フォーム内の入力欄をfor文で取り出すことができる -->
  {% for field in form %} 
  <div class="form-group">
    <!-- そのフィールドインプットタグのidが自動生成されるid_for_labelはそのidをラベルのfor属性に指定してfield.label_tagでラベルの内容今回の場合タイトルと本文がfield.label_tagで表示される -->
    <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
    {{ field }}
    {{ field.errors }}
  </div>
  {% endfor %}
  {% csrf_token %}
  <button type="submit" class="btn btn-dark">送信</button>

</form>

{% endblock %}

blog/templates/blog/page.html
{% load mytag %}
<nav aria-label="Page navigation">
  <ul class="pagination">
 
      {% if page_obj.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}
    
      {% for link_page in page_obj.paginator.page_range %}
        {% if link_page == page_obj.number %}
          <li class="page-item active">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% endif %}
      {% endfor %}
    
      {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    
  </ul>
</nav>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}

<div class="card mb-3">
  <h2 class="card-header bg-dark text-white">{{ post.title }}</h2>
  <div class="card-body">
    <p>{{ post.create_at }}, {{ post.category }}</p>
    <!-- urlizeはURLっぽいものをリンクにしてくれる？ -->
    {{ post.text | linebreaksbr | urlize }}
  </div>
</div>

{% for comment in post.comment_set.all %}

<p>
  {{ comment.name }}<br>
  {{ comment.text |linebreaksbr }}
</p>

{% endfor %}

<a class="btn btn-dark" href="{% url 'blog:comment' post.pk %}">コメント投稿ページへ</a> <!--記事のプライマリーキーを渡す-->

{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}

<!-- 記事をひとつずつ取り出す -->
{% for post in post_list %}

<div class="card mb-3">
  <h2 class="card-header bg-dark text-white">{{ post.title }}</h2>
  <div class="card-body">
    <p>{{ post.create_at }}, {{ post.category }}</p>
    <a href="{% url 'blog:detail' post.pk %}" class="btn btn-dark">続きを読む</a>
  </div>
</div>

{% endfor %}

{% include 'blog/page.html' %}

{% endblock %}